### ISSUE TITLE
백수된김에 사람만나고 다니기

### ISSUE THREAD

**Issue by disjukr** [disjukr/life#11]
## 선생님들 찾아뵙기
- [x] 고등학교 담임쌤
    - [x] 만나뵙는 김에 고등학교 졸업증명서 떼놔야함
        - 2018.02.22 봄방학중이라 선생님은 못 보고 졸업증명서만 떼 옴. 3/2 개학이라고 하니 다시 찾아가볼 예정
- [x] next 담당교수님
    - [x] next 17학년도 졸업식 2018.02.08

## 마루 홍 에드 브라이트 아르 와규팟
- [x] 날짜 정하기
- [x] 2018.02.13

## 끼님이랑 케밥 먹기
- [x] 날짜 정하기
- [x] 이태원 미스터케밥 2018.02.04

## 오행이랑 이수팝픈 ㄱㄱ
- [x] 2018.02.03

## 삵이랑 킨지 카이센동 먹고 방탈출
- [x] 2018.02.07

## 눉님께 타블렛 펜심 받기
- ~[x] 2018.02.09~ 약속 파함

## 삵이랑 블랙팬서
- [x] 2018.02.14

**Comment by xnuk** [comment]
인기인
